name: ytsd
services:
  ytsd:
    image: ytsd:3.0.17
    build:
      context: ../../app
    restart: unless-stopped
    environment:
      TZ: Europe/London
      DATA_DIR: /data
      DOWNLOAD_ROOT: /downloads
      APP_URL: ""
    ports:
      - "8787:8787"
    volumes:
      - ./data:/data
      - ./downloads:/downloads
